### ISSUE TITLE
panic: interface conversion: interface {} is nil, not float64

### ISSUE THREAD

**Issue by Z-13** [tducasse/go-instabot#20]
I geting this:
```
C:\Users\myNAME\go\src\github.com\tducasse\go-instabot>go-instabot -run
2018/08/31 14:09:15 Using config: config/config.json

2018/08/31 14:09:21 Created and saved the key
2018/08/31 14:09:21 Created and saved the session
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
main.loopTags()
        C:/Users/myNAME/go/src/github.com/tducasse/go-instabot/insta.go:131 +0x3a7

main.main()
        C:/Users/myNAME/go/src/github.com/tducasse/go-instabot/instabot.go:14 +0x57
```

How fix it?

Thx.

**Comment by Z-13** [comment]
I fixed it!
It's a problem with tags, before:
```
"tags" : {                              
        "cat" : {                           
            "like" : 10                
        }
```

After:
```
"tags" : {                              
        "cat" : {                           
            "like" : 10,
            "comment" : 0,
            "follow" : 0                  
        }
```
